//Exercise1
//1+2.
let compare=function (compareToTen(num);

	let options = new Promise(compareToTen(resolve, reject) {
		if (num < 10) {
			resolve("Ok");
		} else if (num>10) {
			resolve("Not ok");
		} else {
			reject("Not ok at all");
		}
	});


	options.then(compareToTen(num){
		console.log("This is", JSON.string(value));
	}

	options.catch(compareToTen(num){
		consoloe.log("Oh no", value);
	}

	options.finally(compareToTen(num){
		consoloe.log("Sorry,", value);
	}

//Exercise2
//1.
const promise = new Promise((resolve, reject) => {
	setTimeout(() => {
		resolve("Success");
	}, 4000);
})
//2.//I used the arrow function on secton 1.
//3.
.catch((error) => {
	console.log("Ooops something went wrong");
})

//Exercise3
//1.
let resolved=3;
Promise.resolve('3', rejected).then(
	(resolved) => {
		console.log(resolved); 
	};
  //2.
  Promise.reject(new Error('Boo!')).then(resolved, rejected);